import {
  CloudRain,
  Ghost,
  Users,
  TrendingDown,
  Hourglass,
  Shuffle,
  Flame,
  Brain,
  HeartCrack,
  Activity,
  Crosshair,
  Waves,
  Hammer,
  Swords,
  Medal,
  GraduationCap,
  Scale,
  Target,
  MapPin,
  Dumbbell,
  Heart,
  Gauge,
  Repeat,
  Handshake,
  CalendarCheck,
  RotateCcw,
  CalendarDays,
  CalendarRange,
  Trophy,
  Sparkles,
  type LucideIcon,
} from "lucide-react";

/** Map of string names (used in lib/site.ts) → lucide icon components. */
const ICONS: Record<string, LucideIcon> = {
  CloudRain,
  Ghost,
  Users,
  TrendingDown,
  Hourglass,
  Shuffle,
  Flame,
  Brain,
  HeartCrack,
  Activity,
  Crosshair,
  Waves,
  Hammer,
  Swords,
  Medal,
  GraduationCap,
  Scale,
  Target,
  MapPin,
  Dumbbell,
  Heart,
  Gauge,
  Repeat,
  Handshake,
  CalendarCheck,
  RotateCcw,
  CalendarDays,
  CalendarRange,
  Trophy,
  Sparkles,
};

export function Icon({ name, className }: { name: string; className?: string }) {
  const Cmp = ICONS[name] ?? Sparkles;
  return <Cmp className={className} />;
}
